#!/bin/sh /etc/rc.common

USE_PROCD=1
START=95
STOP=10

start_service() {
    config_load sentinel

    local agreed_eula_version
    config_get agreed_eula_version main agreed_with_eula_version "0"
    [ "$agreed_eula_version" = "0" ] && {
        logger -p 0 -t sentinel-proxy "Proxy failed to start - not" \
                                      "agreed with EULA"
        return 0
    }

    local device_token
    config_get device_token main device_token ""
    sentinel-device-token \
        --validate "${device_token}" \
        --quite \
    || {
        device_token=`sentinel-device-token \
            --create \
            --quite`;
        uci -q set sentinel.main.device_token="${device_token}";
        uci -q commit sentinel.main;
        logger -p 0 -t sentinel-proxy "New device token created";
    }

    echo "device_token = \"${device_token}\"" > \
        /tmp/etc/sentinel-proxy.cfg

    sentinel-certgen certs || {
        logger -p 0 -t sentinel-proxy "Proxy failed to start - certgen" \
                                      "cert check failed"
        return 0
    }

    logger -p 0 -t sentinel-proxy "Starting sentinel proxy"

    procd_open_instance
    procd_set_param command /bin/sh -c 'exec sentinel-proxy'
    procd_set_param respawn 600 5 5
    procd_close_instance
}
