#!/bin/sh
set -e
. /lib/functions.sh
config_load samba


samba_option_migrate() {
	local option="$1"
	local value
	value=$(uci -q get "samba.@samba[0].$option") || return 0
	uci set "samba4.@samba[0].$option=$value"
}

samba_homes() {
	# Note: homes option is no longer supported by Samba4 UCI config
	local homes
	value=$(uci -q get "samba.@samba[0].homes") || return 0
	[ "$homes" = "1" ] || return 0
	create_notification -s update \
		"Samba: Disabling option to share home-directories. Sharing home-directories is discouraged and disabled on Samba4."
	echo "Disabling samba option: Share home-directories" >&2
}

samba_migrate() {
	samba_option_migrate workgroup
	samba_option_migrate description
	samba_option_migrate charset
	samba_option_migrate interface
	samba_homes
}
# We migrate only the first samba.samba section into first (default) samba4.samba section
samba_migrate


sambashare_migrate() {
	local conf="$1"
	local newconf="$2"
	local option="$3"
	local default="$4"
	config_get value "$conf" "$option" "$default"
	[ -n "$value" ] || return 0
	uci set "samba4.$newconf.$option=$value"
}

sambashare_handle() {
	local conf="$1"
	local newconf
	newconf="$(uci add samba4 sambashare)"
	sambashare_migrate "$conf" "$newconf" name
	sambashare_migrate "$conf" "$newconf" path
	sambashare_migrate "$conf" "$newconf" users
	sambashare_migrate "$conf" "$newconf" read_only
	sambashare_migrate "$conf" "$newconf" guest_ok
	sambashare_migrate "$conf" "$newconf" create_mask "0644"
	sambashare_migrate "$conf" "$newconf" dir_mask "0755"
}
config_foreach sambashare_handle sambashare

uci commit samba4
